RethinkRobotics/intera_sdk

- intera_interface/src/intera_interface/gripper.py
Quick fix to avoid gripper calibration when the gripper already calibrated.
The logic now updated to : execute calibrate function if we want the gripper to be calibrated and the gripper is not calibrated yet.
> Fix init gripper calibration setting

- intera_examples/scripts/gripper_joystick.py
- intera_examples/scripts/gripper_keyboard.py
- intera_examples/scripts/head_wobbler.py
- intera_examples/scripts/joint_position_file_playback.py
- intera_examples/scripts/joint_position_joystick.py
- intera_examples/scripts/joint_position_keyboard.py
- intera_examples/scripts/joint_position_waypoints.py
- intera_examples/scripts/joint_torque_springs.py
- intera_examples/scripts/joint_velocity_wobbler.py
- intera_interface/src/intera_interface/robot_enable.py
Resetting the robot's state is only valid if the robot is currently in a Stopped (ERROR) state. This command is actually underlying the Enable / Disabled states, and should be used with caution. Enable & Disable are the preferred methods for stopping the robot.
Additionally, this commit removes unnecessary Disable after examples. In many Baxter examples, it made sense to disable the robot after each example, if the robot was disabled to begin with. On Sawyer, this workflow makes less sense, as the robot is nearly always enabled unless there is an Error or E-Stop. For this reason, the Disabling is removed from the examples.
> Ensure robot is in Stop State before Reset

- intera_examples/scripts/go_to_joint_angles_in_contact.py
- intera_examples/scripts/send_random_trajectory.py
- intera_interface/src/intera_interface/__init__.py
- intera_interface/src/intera_interface/joint_limits.py
- intera_interface/src/intera_motion_interface/__init__.py
- intera_interface/src/intera_motion_interface/motion_waypoint.py
- intera_interface/src/intera_motion_interface/random_walk.py
Created a new python interface for accessing the joint limits. It listens to the /robot/joint_limits topic which may need to be added to the Gazebo simulator work.
This allows users to run the new send_random_trajectory.py script.
> Add JointLimits interface and send_random_trajectory script

- intera_interface/src/intera_motion_interface/motion_trajectory.py
- intera_interface/src/intera_motion_interface/motion_waypoint.py
The FK service is being called on waypoints defined in joint space and with the intention of being run as joint trajectories. These calls are unnecessary. If a trajectory is run as a Cartesian trajectory but the waypoints have been defined in joint space, the FK service will be called when the trajectory is sent to the robot.
> Change when the FK service is called

- intera_examples/scripts/go_to_cartesian_pose.py
QA found a small bug while testing the different script options. A function name was not updated when switching from the RobotInterface to the SDK Limb interface.
> Fixed function tip_state name

- intera_interface/src/intera_interface/limb.py
- intera_interface/src/intera_motion_interface/motion_trajectory.py
- intera_interface/src/intera_motion_interface/motion_waypoint.py
Allow passing of existing Limb objects to MotionWaypoint and
MotionTrajectory classes to avoid extra instantiations of Limb.
> Remove unnecessary Limb class instantiations

- intera_interface/package.xml
This fixes an issue when pulling in the intera_sdk and using it in an overlay and then receiving the error: 
```
Traceback (most recent call last):
File "/opt/rethink/mfg-build/lib/python2.7/dist-packages/intera_motion_interface/__init__.py", line 2, in <module>
from .motion_trajectory import MotionTrajectory
File "/opt/rethink/mfg-build/lib/python2.7/dist-packages/intera_motion_interface/motion_trajectory.py", line 38, in <module>
from motion_waypoint import MotionWaypoint
File "/opt/rethink/mfg-build/lib/python2.7/dist-packages/intera_motion_interface/motion_waypoint.py", line 30, in <module>
from rospy_message_converter import message_converter
ImportError: No module named rospy_message_converter
```
when trying to run python scripts.
> Fix rospy_message_converter dependency issue 

- intera_interface/package.xml
This fixes an issue when pulling in the intera_sdk and using it in an overlay and then receiving the error: 
```
Traceback (most recent call last):
File "/opt/rethink/mfg-build/lib/python2.7/dist-packages/intera_motion_interface/__init__.py", line 2, in <module>
from .motion_trajectory import MotionTrajectory
File "/opt/rethink/mfg-build/lib/python2.7/dist-packages/intera_motion_interface/motion_trajectory.py", line 38, in <module>
from motion_waypoint import MotionWaypoint
File "/opt/rethink/mfg-build/lib/python2.7/dist-packages/intera_motion_interface/motion_waypoint.py", line 30, in <module>
from rospy_message_converter import message_converter
ImportError: No module named rospy_message_converter
```
when trying to run python scripts.
>  Fix rospy_message_converter dependency issue

- intera_interface/src/intera_interface/camera.py
The ROS subscriber buffer size needs to be increased to handle the large incoming images. It also looks like the queue_size parameter was not actually being used.
> Set queue and buffer sizes in camera subscriber

- intera_interface/CMakeLists.txt
This undoes part of #108 which caused build errors because rospy_message_converter is not needed as a build time dependency. This is a cleaner fix than #109.
> Remove rospy_message_converter as a build dependency

- intera_examples/scripts/go_to_joint_angles_in_contact.py
- intera_examples/scripts/set_interaction_options.py
- intera_interface/src/intera_motion_interface/interaction_options.py
This commit introduces two options that will
make interaction control more transparent:
1. Allow users to disable damping in the force mode.
2. Allow users to remove reference resetting.
> Make interaction control more transparent for SDK

- intera_examples/scripts/constrained_zeroG.py
- intera_examples/scripts/go_to_joint_angles_in_contact.py
- intera_examples/scripts/set_interaction_options.py
- intera_interface/src/intera_motion_interface/__init__.py
- intera_interface/src/intera_motion_interface/interaction_options.py
- intera_interface/src/intera_motion_interface/utility_functions.py
This update provides a new option for interaction control
which will allow for arbitrary rotations during constrained zero-G.
A boolean (rotations_for_constrained_zeroG) has been added to
interaction control command and this can be set True while the
commanded orientation is stationary. The actual orientation is
then allowed to change without any limits (only limited by the
joint position limits) with specified rotational stiffness.
For constrained zero-G applications where the stiffnesses for
translations and/or rotations along/about some axes are zero,
setting rotations_for_constrained_zeroG = True will provide
a greater flexibility with stabler behavior. Note that when
it is set to False, the range of rotations is limited to +/-
82 degree. In order to easily demonstrate constrained …
> Allow for arbitrary rotations for constrained zero-G

- intera_examples/scripts/lights_blink.py
The lights example was not preserving
the initial state of the lights when toggling.
This change now preserves the initial lights
state.
> Fix lights example toggle

- intera_examples/scripts/camera_display.py
This commit catches missing cameras in the `camera_display`
example. If one of the cameras is missing, the example would
not perform properly, and report a confusing `OSError`.
Instead, we now catch this error, describe the issue, and
recommend the user contact Rethink Support.
Fixes IN-3629, tested on PV3 with an unplugged head camera.
> Catch and report missing cameras

- intera_examples/scripts/go_to_cartesian_pose.py
- intera_examples/scripts/go_to_joint_angles.py
- intera_examples/scripts/go_to_joint_angles_in_contact.py
- intera_examples/scripts/send_random_trajectory.py
- intera_interface/src/intera_motion_interface/motion_controller_action_client.py
- intera_interface/src/intera_motion_interface/motion_trajectory.py
* Adding timeout functionality to `wait_for_result()` and `send_trajectory()` to block the time before returning.
* Improving documentation and clean-up the code
* Adding documentation to `send_trajectory`
(cherry picked from commit 894c2254543ae68cf9b6beceec3e46be753bf84c)
@asthakukreja and @rethink-forrest, I had to resolve a few conflicts to perform this cherry-pick. Can you please give this a look through to make sure I haven't clobbered anything?
> Adding motion_interface timeout functionality (#118)

- intera_examples/scripts/camera_display.py
- intera_interface/src/intera_interface/camera.py
IROS Fixes to dark image / gain. Add gain, exposure args to
adjust camera gain for dark environments.
* Adds --gain and --exposure args to camera_display example
- enables easy gain fix for dark environments
* Renames camera to cameras
* Fixes Camera to work with fixes to IO state (does it? maybe not)
re IN-4472
> Camera fixes: Add gain, exposure args; fixes for IO fixes

- intera_examples/scripts/camera_display.py
- intera_interface/src/intera_interface/camera.py
Check if each cameras is missing individually and allow interface to
still be used with cameras that are available.
Also make distinction in warning between:
- camera should be there and isn't (Hardware error)
- or, camera wasn't configured to launch in first place
(robot SW launched in Intera mode vs Intera SDK mode)
> Individually check for missing cameras; Allow using available cameras

- intera_examples/scripts/gripper_joystick.py
- intera_examples/scripts/gripper_keyboard.py
- intera_examples/scripts/joint_position_keyboard.py
- intera_interface/src/intera_interface/gripper.py
- Adds `get_dead_zone()` and `get_object_weight()` functions to `Gripper`
class
- Fixed a bug in `object_kg` signals in `Gripper` class
- Adds `set_cmd_velocity()` and `get_cmd_velocity()` in `Gripper` class,
while deprecating `set_velocity()` because it was too ambiguous
- Removed unused `MAX` and `MIN FORCE` constants
- Reports an info message (rather than an error) when no `Gripper` is
plugged in when running `joint_position_keyboard`
- Fixes `gripper_keyboard` example to incrementally open and close
the gripper position, even when at the 0 position
- Fixes `gripper_joystick` example to incrementally open at 0 position,
and removes the force nudging (which could cause jamming)
> Gripper Class and Example updates

- intera_interface/scripts/io_config_editor.py
- intera_interface/src/intera_interface/clicksmart_plate.py
Add reconfigure utility for ClickSmart to Save/Load JSON config files from/to device.
Basic utility to save the JSON config currently on a ClickSmart/EE to a
file, or load a config file onto a ClickSmart/EE.
Allows users to manually edit the configuration of a ClickSmart and
reconfigure the device.
> Reconfigure EndEffectors - Save and Load config file for ClickSmart

- intera_examples/scripts/gripper_keyboard.py
To prevent deprecation warnings from being emitted to the user, this updates
the gripper_keyboard example to use the new interface "set_cmd_velocity".
> Update gripper_keyboard ex to use set_cmd_velocity

- intera_examples/scripts/gripper_joystick.py
Updates the deprecated `Gripper.set_velocity()` call to use the non-deprecated
`set_cmd_velocity()`
> Updates gripper_joystick for new set_cmd_velocity

- intera_examples/scripts/stop_motion_trajectory.py
- intera_interface/src/intera_motion_interface/motion_controller_action_client.py
- intera_interface/src/intera_motion_interface/motion_trajectory.py
This commit adds a script that stops an active motion trajectory. This is useful when the motion controller is running a long trajectory that needs to be canceled.
I also made small modifications to the `MotionTrajectory` and `MotionControllerActionClient` classes to make the `stop()` methods behave more like the `send()` methods.
> Added script to stop the current motion trajectory

- intera_examples/scripts/constrained_zeroG.py
- intera_examples/scripts/set_interaction_options.py
If the e-stop button was pressed while running either the constrained_zeroG or set_interaction_option scripts, the arm could possibly jump after re-enabling the arm. The scripts will now exit after the arm is disabled and send a command to put the arm into position mode.
> When the robot is disabled, put the robot into position mode

- intera_interface/src/intera_interface/camera.py
While setting the camera strobe light is possible with the current SDK, this makes it very straightforward for a user to turn the strobe on and off. See recent comments in #52
> Adds Cognex camera light strobe function

- intera_examples/package.xml
- intera_interface/package.xml
- intera_interface/src/intera_interface/__init__.py
- intera_interface/src/intera_interface/settings.py
- intera_sdk/package.xml
Tested that everything built and ran fine in simulation. Previously, the the enable_robot.py script would not run because of mismatched Intera version numbers.
> Update version to 5.4.0. Remove unused VERSIONS_SDK2GRIPPER

- intera_examples/scripts/constrained_zeroG.py
- intera_examples/scripts/set_interaction_options.py
- intera_interface/src/intera_motion_interface/__init__.py
- intera_interface/src/intera_motion_interface/interaction_options.py
- intera_interface/src/intera_motion_interface/interaction_publisher.py
For these two scripts, I moved most of the code out of the main function into a object class with a send_position_cmd function which is called at shutdown. Setting the publishing rate to zero will the send the interaction command once and exit without sending a position command.
Tested on a robot by stopping the two scripts by pressing both cntr-c and the e-stop button. Tested that commanded line arguments are still properly passed into the interaction command messages.
> Exit Interaction Control mode when exiting scripts

- intera_interface/scripts/send_urdf_fragment.py
xacro_jade is present only in ROS Indigo as it is a backport of xacro from Jade
(cherry picked from commit 2b34620df9c295a6c9e821d95289a38a6f04305b)
> Fix send_urdf_fragment.py for ROS > Indigo (#140)

- intera_examples/scripts/send_random_trajectory.py
- intera_interface/src/intera_motion_interface/random_walk.py
This commit adds an option to the send_random_trajectory script
so that the user can optionally set the RNG seed. This allows
for the script to be called in a repeatable fashion. If the
argument is ommitted, then the default initialization of the
random number generator is used.
> send_random_trajectory.py option to set RNG seed

- intera.sh
Please update the intera.sh file to support kinetic at the default ROS version.
ros_version="kinetic"
Also, will it be possible to add support to colcon builds? For instance, if it cannot find the  "devel/setup.bash" file, then search for the "install/setup.sh" before asking to verify it was build using the catkin_make.
> Update intera.sh with Kinetic
